### ISSUE TITLE
Strange folder behaviour

### ISSUE THREAD

**Issue by alwendya** [dfranx/ImFileDialog#5]
I somehow managed to encounter a bug in the file folder enumerations.
when I open a file dialog, double clicking to the C: drive show me nothing but when opening for exemple the Onedrive shortcut, and go back with the up arrow, i eventually show files in C: view...
Images are better than word, here is a little screenshot series :
![image](https://user-images.githubusercontent.com/68951595/107952480-1a310900-6f9a-11eb-82d0-917e184adc51.png)

By the way : 
- the u8string fix work very well.
- I had to remove the date fix in my case, it is showing year 1652...

Many thanks,
Grégory

**Comment by dfranx** [comment]
Hey! Thank you for the detailed bug report. If you find more, please do report.
It should be fixed now. I think I also fixed the date bug.

**Comment by alwendya** [comment]
Nice, big thanks again.
It's really a nice functionnality added to ImGUI
